# Generated by Django 3.2.5 on 2021-08-07 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=254, null=True)),
                ('type_utilisateur', models.CharField(choices=[('S', 'Secrétaire'), ('C', 'Chef Comptable'), ('A', 'Administrateur')], max_length=1)),
                ('password', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
