# Generated by Django 3.2.5 on 2021-07-28 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apc_beac', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mouvement',
            name='num_tiers2',
            field=models.CharField(max_length=254, null=True),
        ),
    ]
