# Generated by Django 3.2.5 on 2021-07-28 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apc_beac', '0003_auto_20210728_1548'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tiers',
            old_name='num_tiers',
            new_name='tiers',
        ),
        migrations.RemoveField(
            model_name='mouvement',
            name='tiers',
        ),
        migrations.AddField(
            model_name='tiers',
            name='centre',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tiers',
            name='compte',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
