# Generated by Django 3.2.5 on 2021-07-30 03:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apc_beac', '0005_rename_num_tiers_mouvement_tiers'),
    ]

    operations = [
        migrations.AddField(
            model_name='mouvement',
            name='numero',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apc_beac.tiers'),
        ),
    ]
