# Generated by Django 3.2.5 on 2021-07-30 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apc_beac', '0006_mouvement_numero'),
        ('apc_beac', '0007_auto_20210729_2215'),
    ]

    operations = [
    ]
