# Generated by Django 3.2.5 on 2021-08-07 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apc_beac', '0010_remove_mouvement_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='mouvement',
            name='etat',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mouvement',
            name='solde_lettre',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='periode',
            name='annee',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='tiers',
            name='etat',
            field=models.CharField(default='Actif', max_length=254, null=True),
        ),
    ]
